# Generated by Django 5.2.6 on 2026-05-07 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_creditrecord_creditpayment_credititem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('gcash', 'GCash'), ('other', 'Other'), ('credit_payment', 'Credit Payment')], default='cash', max_length=20),
        ),
    ]
