# Generated by Django 5.2.6 on 2026-06-25 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_client_monthly_rate_client_paid_until_date_clientlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.IntegerField(help_text='Number of days this plan covers')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.AddField(
            model_name='clientpayment',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='Which plan this payment covers', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.subscriptionplan'),
        ),
    ]
