# Generated by Django 5.2.6 on 2026-08-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_subscriptionplan_clientpayment_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='subscription_status',
            field=models.CharField(choices=[('free', 'Free'), ('trial', 'Trial'), ('active', 'Active'), ('expired', 'Expired'), ('locked', 'Locked')], default='trial', max_length=20),
        ),
    ]
